// <auto-generated />
using System;
using FileProcessor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileProcessor.Migrations
{
    [DbContext(typeof(FileProcessorDbContext))]
    [Migration("20241025173736_ProductTableSeed")]
    partial class ProductTableSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileProcessor.Data.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApiKey", (string)null);
                });

            modelBuilder.Entity("FileProcessor.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Heads",
                            Description = "A robot head with an unusually large eye and teloscpic neck -- excellent for exploring high spaces.",
                            Discount = 0.20000000000000001,
                            ImageName = "head-big-eye.png",
                            Name = "Large Cyclops",
                            Price = 1220.5
                        },
                        new
                        {
                            Id = 17,
                            Category = "Bases",
                            Description = "A spring base - great for reaching high places.",
                            Discount = 0.0,
                            ImageName = "base-spring.png",
                            Name = "Spring Base",
                            Price = 1190.5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Arms",
                            Description = "An articulated arm with a claw -- great for reaching around corners or working in tight spaces.",
                            Discount = 0.0,
                            ImageName = "arm-articulated-claw.png",
                            Name = "Articulated Arm",
                            Price = 275.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Heads",
                            Description = "A friendly robot head with two eyes and a smile -- great for domestic use.",
                            Discount = 0.20000000000000001,
                            ImageName = "head-friendly.png",
                            Name = "Friendly Bot",
                            Price = 945.0
                        },
                        new
                        {
                            Id = 3,
                            Category = "Heads",
                            Description = "A large three-eyed head with a shredder for a mouth -- great for crushing light medals or shredding documents.",
                            Discount = 0.0,
                            ImageName = "head-shredder.png",
                            Name = "Shredder",
                            Price = 1275.5
                        },
                        new
                        {
                            Id = 16,
                            Category = "Bases",
                            Description = "A single-wheeled base with an accelerometer capable of higher speeds and navigating rougher terrain than the two-wheeled variety.",
                            Discount = 0.10000000000000001,
                            ImageName = "base-single-wheel.png",
                            Name = "Single Wheeled Base",
                            Price = 1190.5
                        },
                        new
                        {
                            Id = 13,
                            Category = "Torsos",
                            Description = "A simple torso with a pouch for carrying items.",
                            Discount = 0.0,
                            ImageName = "torso-pouch.png",
                            Name = "Pouch Torso",
                            Price = 785.0
                        },
                        new
                        {
                            Id = 7,
                            Category = "Arms",
                            Description = "An arm with two independent claws -- great when you need an extra hand. Need four hands? Equip your bot with two of these arms.",
                            Discount = 0.0,
                            ImageName = "arm-dual-claw.png",
                            Name = "Two Clawed Arm",
                            Price = 285.0
                        },
                        new
                        {
                            Id = 4,
                            Category = "Heads",
                            Description = "A simple single-eyed head -- simple and inexpensive.",
                            Discount = 0.0,
                            ImageName = "head-single-eye.png",
                            Name = "Small Cyclops",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 9,
                            Category = "Arms",
                            Description = "An arm with a propeller -- good for propulsion or as a cooling fan.",
                            Discount = 0.10000000000000001,
                            ImageName = "arm-propeller.png",
                            Name = "Propeller Arm",
                            Price = 230.0
                        },
                        new
                        {
                            Id = 15,
                            Category = "Bases",
                            Description = "A rocket base capable of high speed, controlled flight.",
                            Discount = 0.0,
                            ImageName = "base-rocket.png",
                            Name = "Rocket Base",
                            Price = 1520.5
                        },
                        new
                        {
                            Id = 10,
                            Category = "Arms",
                            Description = "A short and stubby arm with a claw -- simple, but cheap.",
                            Discount = 0.0,
                            ImageName = "arm-stubby-claw.png",
                            Name = "Stubby Claw Arm",
                            Price = 125.0
                        },
                        new
                        {
                            Id = 11,
                            Category = "Torsos",
                            Description = "A torso that can bend slightly at the waist and equiped with a heat guage.",
                            Discount = 0.0,
                            ImageName = "torso-flexible-gauged.png",
                            Name = "Flexible Gauged Torso",
                            Price = 1575.0
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bases",
                            Description = "A two wheeled base with an accelerometer for stability.",
                            Discount = 0.0,
                            ImageName = "base-double-wheel.png",
                            Name = "Double Wheeled Base",
                            Price = 895.0
                        },
                        new
                        {
                            Id = 5,
                            Category = "Heads",
                            Description = "A robot head with three oscillating eyes -- excellent for surveillance.",
                            Discount = 0.0,
                            ImageName = "head-surveillance.png",
                            Name = "Surveillance",
                            Price = 1255.5
                        },
                        new
                        {
                            Id = 8,
                            Category = "Arms",
                            Description = "A telescoping arm with a grabber.",
                            Discount = 0.0,
                            ImageName = "arm-grabber.png",
                            Name = "Grabber Arm",
                            Price = 205.5
                        },
                        new
                        {
                            Id = 12,
                            Category = "Torsos",
                            Description = "A less flexible torso with a battery gauge.",
                            Discount = 0.0,
                            ImageName = "torso-gauged.png",
                            Name = "Gauged Torso",
                            Price = 1385.0
                        },
                        new
                        {
                            Id = 18,
                            Category = "Bases",
                            Description = "An inexpensive three-wheeled base. only capable of slow speeds and can only function on smooth surfaces.",
                            Discount = 0.0,
                            ImageName = "base-triple-wheel.png",
                            Name = "Triple Wheeled Base",
                            Price = 700.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
